version: "3.9"

services:
  web:
    container_name: web-server
    image: ghcr.io/ilovebacteria/saminray_task:latest
    env_file:
      - ./.env
    volumes:
      - static_files_volume:/usr/src/app/staticfiles:rw

  proxy:
    container_name: nginx
    image: nginx:1.25-alpine3.18
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files_volume:/usr/share/nginx/html/static/:ro
    depends_on: 
      - web

volumes:
  static_files_volume:
