# Generated by Django 5.1 on 2024-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameserver',
            name='ip',
        ),
        migrations.AddField(
            model_name='nameserver',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
