# Generated by Django 5.0 on 2024-08-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_nameserver_ip_nameserver_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameServer',
            new_name='Server',
        ),
    ]
